trigger:
  - dev

pool:
  vmImage: 'ubuntu-22.04'

variables:
  azureServiceConnection: 'dev'
  webAppName: 'SuperbUiDev'
  keyVaultName: 'SuperbKeyVaultDevRed'
  apiBaseUrl: 'https://superbapidev.azurewebsites.net'

steps:
  - template: ./build.yaml
  - template: ./deploy.yaml
