trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-22.04'

variables:
  azureServiceConnection: 'prod'
  webAppName: 'SuperbUi'
  keyVaultName: 'SuperbKeyVaultBlue'
  apiBaseUrl: 'https://superbapi.azurewebsites.net'

steps:
  - template: ./build.yaml
  - template: ./deploy.yaml
